modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TianKongBen/TheLastSwordYouWillEverNeed-Remastered/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}+mc${minecraft_version}-neoforge"
displayName="${mod_name}"
logoFile= "assets/tlsywen/banner.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"