# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

version=0.1.15
group=net.tianben
java_version=21

# Common
minecraft_version=1.21.1
mod_name=The Last Sword You Will Ever Need: Remastered
mod_author=TianBen
mod_id=tlsywen
license=MIT
credits=
description=This is a remastered version of The Last Sword You Will Ever Need, trying to restore the setting of version 1.7.10 as much as possible!
minecraft_version_range=[1.21.1]
neo_form_version=1.21.1-20240808.144430

# ParchmentMC
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.4+1.21.1
fabric_loader_version=0.16.14

# Forge
forge_version=52.1.0
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.179
neoforge_loader_version_range=[1,)

# Fabric mod dependencies
detailab_fabric_version=5608108